FROM mongo
COPY ./db/ /docker-entrypoint-initdb.d/
ENV MONGO_INITDB_DATABASE=banco
ENV MONGO_INITDB_ROOT_USERNAME=mongo
ENV MONGO_INITDB_ROOT_PASSWORD=1234
ENV ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
ENV ME_CONFIG_MONGODB_ADMINPASSWORD=1234
