name: CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
      
    - run: |
        docker build -t ghcr.io/mauriciolasgon/trabalho_xastre/mysql:5.7 -f Dockerfile .
        docker tag ghcr.io/mauriciolasgon/trabalho_xastre/mysql:5.7  ghcr.io/mauriciolasgon/trabalho_xastre/mysql:${{ github.sha }}
    - run: |
        docker push ghcr.io/mauriciolasgon/trabalho_xastre/mysql:5.7
        docker push ghcr.io/mauriciolasgon/trabalho_xastre/mysql:${{ github.sha }}
